### PR TITLE
Update FroshTools.php

### PR DESCRIPTION
**Pull request by shyim**

### CODE REVIEW

**Comment by shyim** [comment]
@frosh-automation fix-cs

**Comment by shyim** [comment]
@frosh-automation fix-cs

**Comment by shyim** [comment]
@frosh-automation fix-cs

**Comment by shyim** [comment]
@frosh-automation fix-cs

**Comment by shyim** [comment]
@frosh-automation fix-cs

**Comment by schneider-felix** [comment]
@frosh-automation fix-cs

**Pull request closed without merging**
