### PR TITLE
Add APCu check and remove .idea folder in .gitignore

### PR DESCRIPTION
**Pull request by Isengo1989**
Add recommended APCu extension check

Before

`install php8.0-apcu`

After

image

<a href="https://gitpod.io/#https://github.com/FriendsOfShopware/FroshTools/pull/134"></a>

### CODE REVIEW

**Comment by shyim** [comment]
APCu is useless :thinking: . Someone has copied it from SW5 

Or did you had any improve?

**Comment by Isengo1989** [comment]
@shyim I never actually checked the APCu usage :laughing: - just saw there is a requirement in the docs. I guess thats annother PR then :cry:

**Comment by Isengo1989** [comment]
Added this as feedback

image

https://docs.shopware.com/de/migration-de/Systemvoraussetzungen

**Comment by shyim** [comment]
I guess we can close this then

**Pull request closed without merging**
